"""update project

Revision ID: 8a8840cb257b
Revises: ecd13dc0982c
Create Date: 2023-07-05 15:49:59.631036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8840cb257b'
down_revision = 'ecd13dc0982c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
